import {Annuaire} from './annuaire';

export const PERSONNES: Annuaire[] = [
    {
        "id":1,
        "first_name":"Britt",
        "last_name":"Ridgwell",
        "email":"bridgwell0@msu.edu",
        "gender":"Female"
    },
    {
        "id":2,
        "first_name":"Merle",
        "last_name":"Horlock",
        "email":"mhorlock1@ft.com",
        "gender":"Female"
    },
    {
        "id":3,
        "first_name":"Opaline",
        "last_name":"Simonnot",
        "email":"osimonnot2@mac.com",
        "gender":"Female"
    },
    {
        "id":4,
        "first_name":"Rani",
        "last_name":"Lavery",
        "email":"rlavery3@virginia.edu",
        "gender":"Female"
    },
    {
        "id":5,
        "first_name":"Reidar",
        "last_name":"Kellitt",
        "email":"rkellitt4@usatoday.com",
        "gender":"Male"
    },
    {
        "id":6,
        "first_name":"Dar",
        "last_name":"Warland",
        "email":"dwarland5@oracle.com",
        "gender":"Male"
    },
    {
        "id":7,
        "first_name":"Georgette",
        "last_name":"Malley",
        "email":"gmalley6@google.ru",
        "gender":"Female"
    },
    {
        "id":8,
        "first_name":"Carol",
        "last_name":"Rocco",
        "email":"crocco7@cyberchimps.com",
        "gender":"Female"
    },
    {
        "id":9,
        "first_name":"Lynn",
        "last_name":"Millyard",
        "email":"lmillyard8@ted.com",
        "gender":"Male"
    },
    {
        "id":10,
        "first_name":"Bertina",
        "last_name":"Brailsford",
        "email":"bbrailsford9@yellowpages.com",
        "gender":"Female"
    }
];